version: "3"
services:
  input:
    image: nginx:1.16.0-alpine
    container_name: sapporo-fileserver-input
    restart: always
    volumes:
      - ${PWD}/data/input_data:/data
      - ${PWD}/etc/nginx/cache:/var/cache/nginx
      - ${PWD}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/etc/nginx/run:/var/run/nginx
      - ${PWD}/log/nginx:/var/log/nginx
    user: ${UID:-0}:${GID:-0}
    networks:
      - sapporo
    ports:
      - ${SAPPORO_FILESERVER_INPUT_PORT:-1123}:8080
  output:
    image: minio/minio:RELEASE.2019-07-17T22-54-12Z
    container_name: sapporo-fileserver-output
    restart: always
    volumes:
      - ${PWD}/data/output_data:/data
      - ${PWD}/log/minio:/var/log/minio
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-access_key}
      - MINIO_GROUPNAME=${GID:-0}
      - MINIO_HTTP_TRACE=/var/log/minio/access.log
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-secret_access_key}
      - MINIO_USERNAME=${UID:-0}
    user: ${UID:-0}:${GID:-0}
    command: ["server", "--address", "0.0.0.0:8080", "/data"]
    networks:
      - sapporo
    ports:
      - ${SAPPORO_FILESERVER_OUTPUT_PORT:-1124}:8080

networks:
  sapporo:
    external:
      name: sapporo-network
